## Numpy

In [1]:
import numpy as np

In [2]:
#Creating an numpy array
a = np.array([1,2,3,4,5])
print(a)
print(type(a))  

print(a.shape)  #shape of array

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
b = np.array([[1],[2],[3],[4],[5]]) #1D aaray
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [6]:
c = np.array([[1,2,3],[4,5,6]]) #2D array
print(c)
print(c.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [7]:
#Array of Zeros
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
#Array of ones
b = np.ones((2,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
#Array of some constants
c = np.full((3,2),5)
print(c)

[[5 5]
 [5 5]
 [5 5]]


In [10]:
#Identity Martix - Size/Square Martix
d = np.eye(4)  #Eye func is use to create an identity martix of size 4*4 
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [18]:
#Random Martix
randomMartix = np.random.random((2,3)) #random matrix of size 2*3
print(randomMartix)

[[0.08447512 0.52904556 0.09140525]
 [0.49998761 0.86685478 0.10318029]]


In [24]:
randomMartix[1,1] = 3  #updating the value of 2nd row 2nd column with 3 using slicing 
print(randomMartix)

[[0.08447512 0.52904556 0.09140525]
 [0.49998761 3.         0.10318029]]


In [28]:
#Data types
print(d.dtype)

float64


In [30]:
x = np.array([[1,2],[3,4]])
y = np.array(([5,6],[7,8]))

print(x+y)  #Adding matrix x and y
#or
print(np.add(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [33]:
#Martix Multiplication / Dot Prodaucts
print(x)
print(y)

print(x.dot(y))
#or
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [51]:
#Multiplication(Dot Product) of Vectors => Scalar
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(a.dot(b))

30


In [52]:
print(a)
print(sum(a)) #sum of numbers

[1 2 3 4]
10


In [38]:
print(x)

[[1 2]
 [3 4]]


In [53]:
print(np.sum(x,axis=0)) #sum of columns
print(np.sum(x,axis=1)) #sum of rows

[4 6]
[3 7]


In [54]:
#Stacking of arrays
print(a)
b = b**2
print(b)

[1 2 3 4]
[ 1  4  9 16]


In [58]:
i = np.stack((a,b),axis=1)

array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16]])

In [62]:
#Reshape a NUmpy Array
print(i.reshape(-1,4))

[[ 1  1  2  4]
 [ 3  9  4 16]]


### Numpy Random Module

In [65]:
a = np.arange(10) + 5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [66]:
np.random.shuffle(a)
print(a)

[ 7 14  9 10  6 13 12  5  8 11]


In [69]:
a = np.random.randint(5,10,3)
print(a)

[7 8 7]


In [71]:
#Randomly pick one element from a array
element = np.random.choice([1,3,5,7,3,2])
print(element)

3


### Statistics in Numpy

In [74]:
a = np.array([[1,2,3,4],[7,4,2,1]])
print(np.min(a)) #minimum element in the array
print(np.max(a)) #maximum element in the array

1
7


In [75]:
#Specify axis for the direction in case of multi-dimensional array
print(np.min(a,axis=0))
print(np.min(a,axis=1))

[1 2 2 1]
[1 1]


In [76]:
# Mean
b = np.array([1,2,3,4,5])
m = sum(b)/5
print(m)

3.0


In [77]:
print(np.mean(b))

3.0


In [78]:
#Median
c = np.array([1,4,6,7,0])
print(np.median(c))

4.0


In [80]:
# Mean v Average
print(np.mean(c))

w = np.array([1,2,3,4,5])
print(np.average(c,weights = w))

3.6
3.6666666666666665


In [81]:
#Standard Deviation
u = np.mean(c)
myStd = np.sqrt(np.mean(abs(c-u)**2))
print(myStd)

2.727636339397171


In [83]:
#Inbuilt func of SD
sd = np.std(c)
print(sd)

2.727636339397171


In [85]:
#Variance
print(myStd**2)
print(np.var(c))  #inbuilt func

7.44
7.44
